// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvFTTC7QvPLemFmMqadkWwhvPWcs4F8Qw',
    appId: '1:257010407670:web:54dbed272e89febb34f4d7',
    messagingSenderId: '257010407670',
    projectId: 'practica3-d3f35',
    authDomain: 'practica3-d3f35.firebaseapp.com',
    storageBucket: 'practica3-d3f35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVRcHCbMEsN_vH8ggQXs2yoi4se2yvRRo',
    appId: '1:257010407670:android:f3408bf23a30ab5034f4d7',
    messagingSenderId: '257010407670',
    projectId: 'practica3-d3f35',
    storageBucket: 'practica3-d3f35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDljear7yV7_5Lw3hHnqy5r9helqwhI7dY',
    appId: '1:257010407670:ios:a19106ae7250d87f34f4d7',
    messagingSenderId: '257010407670',
    projectId: 'practica3-d3f35',
    storageBucket: 'practica3-d3f35.appspot.com',
    iosBundleId: 'com.example.practica35c',
  );
}
